(define (main args)
  (let ((target (car (last-pair (string-split (car args) "/")))))
    (display target)
    (newline)
    (let ((rxobj (rxmatch #/(.*)\./ target)))
      (display rxobj)
      (newline)
      (let ((filename (regexp-replace #/-test/ (rxobj 1) "")))
        (display filename)
        (newline)
        (display (string-join (list "./" filename) ""))
        (load (string-join (list "./" filename) ""))))))

(print a)
